name: Python package

on: [push]

jobs:

  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install black isort flake8 bandit[toml]
    - run: python -m black . --check
    - run: python -m isort . --check-only
    - run: python -m flake8 .
    - run: python -m bandit . --recursive -c pyproject.toml

  test-3-8:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2019]
        python-version: ['3.8', '3.9']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install -U pip wheel poetry==1.8.5
        python -m poetry install -E ml -E gui
    - name: Run tests
      run: |
        python -m poetry run python -OO -m unittest discover -v -s tests

  test-3-10:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2019]
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install -U pip wheel poetry==1.8.5
        python -m poetry install -E ml -E gui
    - name: Run tests
      run: |
        python -m poetry run python -OO -m unittest discover -v -s tests
